#!/usr/bin/env npx tsx
/**
 * S&P 500 Backtest Showcase
 *
 * Runs multiple strategies on US ETF data, then applies TrendCraft's
 * advanced analytics: robustness scoring, alpha decay analysis,
 * pairs trading analysis, and cross-asset correlation.
 *
 * Prerequisites:
 *   1. Fetch data first: npx tsx fetch-data.ts
 *   2. Run showcase:     npx tsx run-showcase.ts
 *
 * Output: ./reports/showcase-report.md
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  // Alpha Decay
  analyzeAlphaDecay,
  // Cross-Asset Correlation
  analyzeCorrelation,
  // Pairs Trading
  analyzePair,
  and,
  bollingerBreakout,
  createObservationsFromTrades,
  deadCrossCondition,
  // Explainability
  explainSignal,
  // Conditions (backtest conditions, not signal functions)
  goldenCrossCondition,
  macdCrossDown,
  macdCrossUp,
  perfectOrderActiveBullish,
  perfectOrderCollapsed,
  // Robustness
  quickRobustnessScore,
  rsiAbove,
  rsiBelow,
  // Backtest engine
  runBacktest,
} from "../../src/index";

import { loadCsvFile } from "../../src/screening";
import type { BacktestResult, Condition, NormalizedCandle } from "../../src/types";

// --- Configuration ---

const DATA_DIR = resolve(import.meta.dirname, "data");
const REPORTS_DIR = resolve(import.meta.dirname, "reports");
const CAPITAL = 100_000;

type StrategyDef = {
  name: string;
  description: string;
  entry: Condition;
  exit: Condition;
  stopLoss?: number;
  takeProfit?: number;
  trailingStop?: number;
};

const STRATEGIES: StrategyDef[] = [
  {
    name: "Golden Cross (50/200)",
    description: "SMA 5/25 golden cross → dead cross, 5% stop loss",
    entry: goldenCrossCondition(5, 25),
    exit: deadCrossCondition(5, 25),
    stopLoss: 5,
  },
  {
    name: "RSI Mean Reversion",
    description: "Buy RSI < 30, sell RSI > 70, 3% trailing stop",
    entry: rsiBelow(30),
    exit: rsiAbove(70),
    trailingStop: 3,
  },
  {
    name: "Perfect Order Trend",
    description: "Enter bullish perfect order, exit on collapse, 7% SL",
    entry: perfectOrderActiveBullish({ periods: [5, 25, 75] }),
    exit: perfectOrderCollapsed({ periods: [5, 25, 75] }),
    stopLoss: 7,
  },
  {
    name: "MACD Momentum",
    description: "MACD signal line crossover, 4% stop loss",
    entry: macdCrossUp(),
    exit: macdCrossDown(),
    stopLoss: 4,
  },
  {
    name: "Bollinger Breakout",
    description: "Upper band breakout → lower band exit, 3% SL + 5% trailing",
    entry: bollingerBreakout("upper"),
    exit: bollingerBreakout("lower"),
    stopLoss: 3,
    trailingStop: 5,
  },
];

// --- Data Loading ---

function loadAllData(): Map<string, NormalizedCandle[]> {
  if (!existsSync(DATA_DIR)) {
    console.error(`Data directory not found: ${DATA_DIR}`);
    console.error("Run 'npx tsx fetch-data.ts' first.");
    process.exit(1);
  }

  const files = readdirSync(DATA_DIR).filter((f) => f.endsWith(".csv"));
  if (files.length === 0) {
    console.error("No CSV files found. Run 'npx tsx fetch-data.ts' first.");
    process.exit(1);
  }

  const data = new Map<string, NormalizedCandle[]>();
  for (const file of files) {
    try {
      const { ticker, candles } = loadCsvFile(resolve(DATA_DIR, file));
      if (candles.length >= 200) {
        data.set(ticker, candles);
        console.log(`  Loaded ${ticker}: ${candles.length} candles`);
      }
    } catch {
      // Skip invalid files
    }
  }

  return data;
}

// --- Backtest Runner ---

type StrategyResult = {
  strategy: string;
  results: Map<string, BacktestResult>;
};

function runStrategies(data: Map<string, NormalizedCandle[]>): StrategyResult[] {
  const allResults: StrategyResult[] = [];

  for (const strategy of STRATEGIES) {
    const results = new Map<string, BacktestResult>();

    for (const [symbol, candles] of data) {
      const result = runBacktest(candles, strategy.entry, strategy.exit, {
        capital: CAPITAL,
        stopLoss: strategy.stopLoss,
        takeProfit: strategy.takeProfit,
        trailingStop: strategy.trailingStop,
      });
      results.set(symbol, result);
    }

    allResults.push({ strategy: strategy.name, results });
  }

  return allResults;
}

// --- Report Generation ---

function pct(n: number): string {
  return `${n >= 0 ? "+" : ""}${n.toFixed(2)}%`;
}

function generateReport(
  data: Map<string, NormalizedCandle[]>,
  strategyResults: StrategyResult[],
): string {
  const lines: string[] = [];
  const now = new Date().toISOString().split("T")[0];

  lines.push("# S&P 500 Backtest Showcase");
  lines.push("");
  lines.push(`> Generated by TrendCraft on ${now}`);
  lines.push("");

  // --- Data Summary ---
  lines.push("## Data Summary");
  lines.push("");
  lines.push("| Symbol | Period | Candles |");
  lines.push("|--------|--------|---------|");
  for (const [symbol, candles] of data) {
    const start = new Date(candles[0].time).toISOString().split("T")[0];
    const end = new Date(candles[candles.length - 1].time).toISOString().split("T")[0];
    lines.push(`| ${symbol} | ${start} — ${end} | ${candles.length} |`);
  }
  lines.push("");

  // --- Buy & Hold Benchmark ---
  const buyAndHold = new Map<string, number>();
  for (const [symbol, candles] of data) {
    const firstClose = candles[0].close;
    const lastClose = candles[candles.length - 1].close;
    buyAndHold.set(symbol, ((lastClose - firstClose) / firstClose) * 100);
  }

  lines.push("## Buy & Hold Benchmark");
  lines.push("");
  lines.push("| Symbol | Buy & Hold Return | Period |");
  lines.push("|--------|-------------------|--------|");
  for (const [symbol, candles] of data) {
    const start = new Date(candles[0].time).toISOString().split("T")[0];
    const end = new Date(candles[candles.length - 1].time).toISOString().split("T")[0];
    const bh = buyAndHold.get(symbol) ?? 0;
    lines.push(`| ${symbol} | ${pct(bh)} | ${start} — ${end} |`);
  }
  lines.push("");

  // --- Strategy Comparison ---
  lines.push("## Strategy Comparison");
  lines.push("");

  for (const { strategy, results } of strategyResults) {
    const strategyDef = STRATEGIES.find((s) => s.name === strategy);
    if (!strategyDef) continue;
    lines.push(`### ${strategy}`);
    lines.push("");
    lines.push(`> ${strategyDef.description}`);
    lines.push("");
    lines.push("| Symbol | Return | vs B&H | Trades | Win Rate | Max DD | Sharpe | PF |");
    lines.push("|--------|--------|--------|--------|----------|--------|--------|-----|");

    for (const [symbol, result] of results) {
      const bh = buyAndHold.get(symbol) ?? 0;
      const alpha = result.totalReturnPercent - bh;
      lines.push(
        `| ${symbol} | ${pct(result.totalReturnPercent)} | ${pct(alpha)} | ${result.tradeCount} | ${result.winRate.toFixed(1)}% | ${result.maxDrawdown.toFixed(1)}% | ${result.sharpeRatio.toFixed(3)} | ${result.profitFactor.toFixed(2)} |`,
      );
    }
    lines.push("");
  }

  // --- Best Strategy per Symbol ---
  lines.push("## Best Strategy per Symbol");
  lines.push("");
  lines.push("| Symbol | Best Strategy | Return | B&H | Alpha | Beat B&H? |");
  lines.push("|--------|---------------|--------|-----|-------|-----------|");

  for (const [symbol] of data) {
    let bestStrategy = "";
    let bestReturn = Number.NEGATIVE_INFINITY;

    for (const { strategy, results } of strategyResults) {
      const r = results.get(symbol);
      if (r && r.totalReturnPercent > bestReturn) {
        bestReturn = r.totalReturnPercent;
        bestStrategy = strategy;
      }
    }

    const bh = buyAndHold.get(symbol) ?? 0;
    const alpha = bestReturn - bh;
    const beat = bestReturn > bh ? "Yes" : "**No**";
    lines.push(
      `| ${symbol} | ${bestStrategy} | ${pct(bestReturn)} | ${pct(bh)} | ${pct(alpha)} | ${beat} |`,
    );
  }
  lines.push("");

  // --- Robustness Scores ---
  lines.push("## Robustness Analysis");
  lines.push("");
  lines.push("Using `quickRobustnessScore()` on SPY results for each strategy:");
  lines.push("");
  lines.push(
    "| Strategy | Grade | Score | Monte Carlo | Trade Consistency | Drawdown Resilience |",
  );
  lines.push(
    "|----------|-------|-------|-------------|-------------------|---------------------|",
  );

  for (const { strategy, results } of strategyResults) {
    const spyResult = results.get("SPY");
    if (!spyResult || spyResult.tradeCount < 5) {
      lines.push(`| ${strategy} | N/A | — | — | — | — |`);
      continue;
    }

    const robustness = quickRobustnessScore(spyResult, { seed: 42 });
    const { monteCarlo, tradeConsistency, drawdownResilience } = robustness.dimensions;
    lines.push(
      `| ${strategy} | **${robustness.grade}** | ${robustness.compositeScore.toFixed(1)} | ${monteCarlo.score.toFixed(1)} | ${tradeConsistency.score.toFixed(1)} | ${drawdownResilience.score.toFixed(1)} |`,
    );
  }
  lines.push("");

  // --- Alpha Decay ---
  lines.push("## Alpha Decay Analysis");
  lines.push("");
  lines.push("Checking if strategy predictive power degrades over time (SPY):");
  lines.push("");
  lines.push("| Strategy | Status | IC Trend | Hit Rate (recent) | Structural Breaks |");
  lines.push("|----------|--------|----------|-------------------|-------------------|");

  for (const { strategy, results } of strategyResults) {
    const spyResult = results.get("SPY");
    if (!spyResult || spyResult.trades.length < 30) {
      lines.push(`| ${strategy} | N/A | — | — | — |`);
      continue;
    }

    const observations = createObservationsFromTrades(spyResult.trades);
    const decay = analyzeAlphaDecay(observations, { window: 20, minObservations: 15 });

    const status = decay.assessment.status;
    const icTrend = decay.assessment.icTrend >= 0 ? "Stable" : "Declining";
    const recentHR =
      decay.rollingHitRate.length > 0
        ? `${(decay.rollingHitRate[decay.rollingHitRate.length - 1].hitRate * 100).toFixed(1)}%`
        : "—";
    const breaks = decay.breaks.length;

    lines.push(`| ${strategy} | **${status}** | ${icTrend} | ${recentHR} | ${breaks} |`);
  }
  lines.push("");

  // --- Signal Explainability ---
  const spyCandlesForExplain = data.get("SPY");
  if (spyCandlesForExplain) {
    lines.push("## Signal Explainability (SPY)");
    lines.push("");
    lines.push(
      "Using `explainSignal()` to trace why each strategy's most recent trade was triggered:",
    );
    lines.push("");

    for (const strategyDef of STRATEGIES) {
      const result = strategyResults.find((r) => r.strategy === strategyDef.name);
      const spyResult = result?.results.get("SPY");

      if (!spyResult || spyResult.trades.length === 0) continue;

      // Find the candle index where the last trade's entry signal actually fired
      // We scan backward from entryTime to find where the condition evaluates true
      const lastTrade = spyResult.trades[spyResult.trades.length - 1];
      let entryIdx = spyCandlesForExplain.findIndex((c) => c.time >= lastTrade.entryTime);

      // fillMode=next-bar-open means signal fired on the bar before entryTime
      if (entryIdx > 0) entryIdx--;

      if (entryIdx < 0) continue;

      const explanation = explainSignal(
        spyCandlesForExplain,
        entryIdx,
        strategyDef.entry,
        strategyDef.exit,
        { includeValues: true },
      );

      const date = new Date(explanation.time).toISOString().split("T")[0];

      lines.push(`### ${strategyDef.name}`);
      lines.push("");
      lines.push(
        `**Date**: ${date} | **Signal**: ${explanation.signalType} | **Fired**: ${explanation.fired}`,
      );
      lines.push("");
      lines.push(`> ${explanation.narrative}`);
      lines.push("");

      if (explanation.contributions.length > 0) {
        lines.push("| Condition | Passed | Indicator Values |");
        lines.push("|-----------|--------|------------------|");

        for (const contrib of explanation.contributions) {
          const values = Object.entries(contrib.indicatorValues)
            .map(([k, v]) => {
              if (typeof v === "number") return `${k}: ${v.toFixed(2)}`;
              if (typeof v === "object" && v !== null) {
                // Flatten object values (e.g., MACD, Bollinger)
                return Object.entries(v as Record<string, unknown>)
                  .filter(([, val]) => typeof val === "number")
                  .map(([subKey, val]) => `${subKey}: ${(val as number).toFixed(2)}`)
                  .join(", ");
              }
              return `${k}: ${v}`;
            })
            .filter(Boolean)
            .join(", ");
          lines.push(`| ${contrib.name} | ${contrib.passed ? "Yes" : "No"} | ${values || "—"} |`);
        }
        lines.push("");
      }
    }
  }

  // --- Pairs Trading Analysis ---
  const spyCandles = data.get("SPY");
  const qqqCandles = data.get("QQQ");

  if (spyCandles && qqqCandles) {
    lines.push("## Pairs Trading: SPY vs QQQ");
    lines.push("");

    const spySeries = spyCandles.map((c) => ({ time: c.time, value: c.close }));
    const qqqSeries = qqqCandles.map((c) => ({ time: c.time, value: c.close }));

    const pairs = analyzePair(spySeries, qqqSeries);

    lines.push(
      `- **Cointegrated**: ${pairs.cointegration.isCointegrated ? "Yes" : "No"} (p-value: ${pairs.cointegration.pValue.toFixed(4)})`,
    );
    lines.push(`- **Hedge Ratio**: ${pairs.cointegration.hedgeRatio.toFixed(4)}`);
    lines.push(`- **Half-life**: ${pairs.meanReversion.halfLife.toFixed(1)} days`);
    lines.push(`- **Mean Reversion Speed (λ)**: ${pairs.meanReversion.lambda.toFixed(4)}`);
    lines.push(
      `- **Current Z-Score**: ${pairs.spreadSeries.length > 0 ? pairs.spreadSeries[pairs.spreadSeries.length - 1].zScore.toFixed(2) : "N/A"}`,
    );
    lines.push(`- **Signals Generated**: ${pairs.signals.length}`);
    lines.push("");

    if (pairs.signals.length > 0) {
      lines.push("Recent signals:");
      lines.push("");
      lines.push("| Date | Type | Z-Score |");
      lines.push("|------|------|---------|");

      const recentSignals = pairs.signals.slice(-10);
      for (const sig of recentSignals) {
        const date = new Date(sig.time).toISOString().split("T")[0];
        lines.push(`| ${date} | ${sig.type} | ${sig.zScore.toFixed(2)} |`);
      }
      lines.push("");
    }
  }

  // --- Cross-Asset Correlation ---
  lines.push("## Cross-Asset Correlation Matrix");
  lines.push("");

  const symbols = Array.from(data.keys());
  const seriesMap = new Map<string, Array<{ time: number; value: number }>>();
  for (const [symbol, candles] of data) {
    seriesMap.set(
      symbol,
      candles.map((c) => ({ time: c.time, value: c.close })),
    );
  }

  // Build correlation matrix
  lines.push(`| | ${symbols.join(" | ")} |`);
  lines.push(`|---|${symbols.map(() => "---").join("|")}|`);

  for (const symA of symbols) {
    const row = [symA];
    const serA = seriesMap.get(symA);
    if (!serA) continue;

    for (const symB of symbols) {
      if (symA === symB) {
        row.push("1.00");
        continue;
      }

      const serB = seriesMap.get(symB);
      if (!serB) {
        row.push("—");
        continue;
      }
      try {
        const corr = analyzeCorrelation(serA, serB, { window: 60 });
        row.push(corr.summary.avgCorrelation.toFixed(2));
      } catch {
        row.push("—");
      }
    }

    lines.push(`| ${row.join(" | ")} |`);
  }
  lines.push("");

  // --- Footer ---
  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by [TrendCraft](https://github.com/sawapi/trendcraft) — zero-dependency TypeScript technical analysis library*",
  );
  lines.push("");

  return lines.join("\n");
}

// --- Main ---

async function main() {
  console.log("=== S&P 500 Backtest Showcase ===\n");

  // 1. Load data
  console.log("Loading data...");
  const data = loadAllData();
  console.log(`\nLoaded ${data.size} symbols\n`);

  // 2. Run strategies
  console.log("Running strategies...");
  const strategyResults = runStrategies(data);
  console.log(`\nCompleted ${STRATEGIES.length} strategies × ${data.size} symbols\n`);

  // 3. Generate report
  console.log("Generating report...");
  const report = generateReport(data, strategyResults);

  // Save report
  const reportPath = resolve(REPORTS_DIR, "showcase-report.md");
  writeFileSync(reportPath, report, "utf-8");
  console.log(`\nReport saved to: ${reportPath}`);

  // Also print summary to console
  const spyCandles = data.get("SPY");
  const spyBH = spyCandles
    ? ((spyCandles[spyCandles.length - 1].close - spyCandles[0].close) / spyCandles[0].close) * 100
    : 0;

  console.log(`\n${"=".repeat(70)}`);
  console.log(`SUMMARY: SPY Results (Buy & Hold: ${pct(spyBH)})`);
  console.log("=".repeat(70));

  for (const { strategy, results } of strategyResults) {
    const spy = results.get("SPY");
    if (spy) {
      const alpha = spy.totalReturnPercent - spyBH;
      const beat = alpha >= 0 ? "BEAT" : "LOST";
      console.log(
        `  ${strategy.padEnd(25)} ${pct(spy.totalReturnPercent).padStart(10)}  α: ${pct(alpha).padStart(9)}  ${beat}  Sharpe: ${spy.sharpeRatio.toFixed(3)}  Trades: ${spy.tradeCount}`,
      );
    }
  }
}

main();
