/**
 * TrendCraft - Financial Data Analysis Library
 *
 * @packageDocumentation
 */

export type {
  LiquiditySweepConditionOptions,
  OrderBlockConditionOptions,
  PatternConditionOptions,
  PerfectOrderConditionOptions,
  PerfectOrderEnhancedConditionOptions,
  RangeBoundConditionOptions,
  RSConditionOptions,
  ScaledBacktestOptions,
  ValidatedCrossOptions,
} from "./backtest";
// Backtest conditions
// Range-Bound backtest conditions
// Advanced Volume conditions
// Multi-Timeframe (MTF) conditions
// Volatility Regime conditions
// Relative Strength (RS) conditions
// Price Pattern conditions
// Smart Money Concepts (SMC) conditions
// Perfect Order Pullback conditions
export {
  adxStrong,
  alwaysFalse,
  // Always-true / always-false primitives
  alwaysTrue,
  // Combinators
  and,
  anyBearishPattern,
  anyBullishPattern,
  anyPatternConfidenceAbove,
  // ATR% Filter conditions
  atrPercentAbove,
  atrPercentBelow,
  atrPercentileAbove,
  atrPercentileBelow,
  BENCHMARK_CACHE_KEY,
  // Portfolio / Multi-Asset Backtest
  batchBacktest,
  bearFlagDetected,
  bearishHarmonicDetected,
  bearishVolumeDivergence,
  bollingerBreakout,
  bollingerTouch,
  breakdownVal,
  breakoutRiskDown,
  breakoutRiskUp,
  breakoutVah,
  bullFlagDetected,
  bullishHarmonicDetected,
  bullishVolumeDivergence,
  channelDetected,
  // CMF conditions
  cmfAbove,
  cmfBelow,
  cupHandleDetected,
  deadCross as deadCrossCondition,
  dmiBearish,
  // DMI/ADX conditions
  dmiBullish,
  doubleBottomDetected,
  doubleTopDetected,
  flagDetected,
  // Preset conditions
  goldenCross as goldenCrossCondition,
  harmonicPatternDetected,
  hasActiveOrderBlocks,
  hasRecentSweeps,
  headShouldersDetected,
  inRangeBound,
  inValueArea,
  inverseHeadShouldersDetected,
  liquiditySweepDetected,
  liquiditySweepRecovered,
  macdCrossDown,
  macdCrossUp,
  mansfieldRSAbove,
  mansfieldRSBelow,
  monthlyPriceAboveSma,
  monthlyPriceBelowSma,
  monthlyRsiAbove,
  monthlyRsiBelow,
  monthlyTrendStrong,
  mtfCondition,
  mtfDowntrend,
  mtfPriceAboveEma,
  mtfPriceAboveSma,
  mtfPriceBelowSma,
  mtfRsiAbove,
  mtfRsiBelow,
  mtfTrendStrong,
  mtfUptrend,
  nearPoc,
  not,
  obvCrossDown,
  obvCrossUp,
  obvFalling,
  // OBV conditions
  obvRising,
  or,
  orderBlockCreated,
  orderBlockMitigated,
  outperformanceAbove,
  outperformanceBelow,
  patternConfidenceAbove,
  patternConfirmed,
  patternDetected,
  patternWithinBars,
  pbEntry,
  pbrAbove,
  pbrBelow,
  pbrBetween,
  perAbove,
  // Fundamental conditions
  perBelow,
  perBetween,
  perfectOrderActiveBearish,
  perfectOrderActiveBullish,
  perfectOrderBearish,
  perfectOrderBearishConfirmed,
  perfectOrderBreakdown,
  // Perfect Order conditions
  perfectOrderBullish,
  // Enhanced Perfect Order conditions
  perfectOrderBullishConfirmed,
  perfectOrderCollapsed,
  perfectOrderConfirmationFormed,
  perfectOrderMaCollapsed,
  perfectOrderPreBearish,
  perfectOrderPreBullish,
  perfectOrderPullbackEntry,
  perfectOrderPullbackSellEntry,
  // PO+ and PB entry conditions
  poPlusEntry,
  poPlusPbEntry,
  portfolioBacktest,
  priceAbovePoc,
  priceAboveSma,
  priceAtBearishOrderBlock,
  priceAtBullishOrderBlock,
  priceAtOrderBlock,
  priceBelowPoc,
  priceBelowSma,
  priceDroppedAtr,
  rangeBreakout,
  rangeConfirmed,
  rangeForming,
  rangeScoreAbove,
  regimeConfidenceAbove,
  regimeIs,
  regimeNot,
  rsAbove,
  rsBelow,
  rsFalling,
  rsiAbove,
  rsiBelow,
  rsNewHigh,
  rsNewLow,
  rsRatingAbove,
  rsRatingBelow,
  rsRising,
  // Engine
  runBacktest,
  runBacktestScaled,
  stochAbove,
  // Stochastics conditions
  stochBelow,
  stochCrossDown,
  stochCrossUp,
  sweepDepthAbove,
  tightRange,
  triangleDetected,
  validatedDeadCross,
  // Validated conditions (with damashi detection)
  validatedGoldenCross,
  volatilityAbove,
  volatilityBelow,
  volatilityContracting,
  volatilityExpanding,
  // Volume conditions
  volumeAboveAvg,
  volumeAnomalyCondition,
  volumeConfirmsTrend,
  volumeDivergence,
  volumeExtreme,
  volumeRatioAbove,
  volumeTrendConfidence,
  wedgeDetected,
  weeklyDowntrend,
  weeklyPriceAboveEma,
  weeklyPriceAboveSma,
  weeklyPriceBelowSma,
  weeklyRsiAbove,
  weeklyRsiBelow,
  weeklyTrendStrong,
  weeklyUptrend,
} from "./backtest";
export type { ParseFundamentalsOptions } from "./core/fundamentals";
// Fundamentals utilities
export {
  createFundamentalsMap,
  getFundamentalsAt,
  parseFundamentals,
} from "./core/fundamentals";
// Indicator Cache
export { createCachedIndicators, IndicatorCache } from "./core/indicator-cache";
// MTF context utilities
export {
  buildMtfIndexMap,
  createMtfContext,
  getCurrentMtfIndicatorValue,
  getMtfCandle,
  getMtfIndicator,
  getMtfTimeframes,
  hasMtfTimeframe,
  setMtfIndicator,
  updateMtfIndices,
} from "./core/mtf-context";
// Core utilities
export {
  getPrice,
  getPriceSeries,
  normalizeCandle,
  normalizeCandles,
  normalizeTime,
} from "./core/normalize";
export { getPeriodStart, parseTimeframe, resample } from "./core/resample";
// Statistics utilities
export { kurtosis, median, normalCdf, percentile, quartiles, skewness } from "./core/statistics";
export type { AnalysisResult } from "./core/trendcraft";
// Fluent API
export { MtfStrategyBuilder, StrategyBuilder, TrendCraft, TrendCraftMtf } from "./core/trendcraft";
export type {
  AdaptiveBollingerOptions,
  AdaptiveBollingerValue,
  AdaptiveMaOptions,
  AdaptiveMaValue,
  // Adaptive Indicator types
  AdaptiveRsiOptions,
  AdaptiveRsiValue,
  AdaptiveStochasticsOptions,
  AdaptiveStochasticsValue,
  AdxrOptions,
  AlmaOptions,
  AlternatingSwingPoint,
  AnchoredVwapOptions,
  AnchoredVwapValue,
  AndrewsPitchforkOptions,
  AndrewsPitchforkValue,
  AroonOptions,
  AroonValue,
  AtrFilterOptions,
  AtrFilterResult,
  // Auto Trend Line / Channel / Fibonacci Extension / Pitchfork types
  AutoTrendLineOptions,
  AutoTrendLineValue,
  AwesomeOscillatorOptions,
  BalanceOfPowerOptions,
  BenchmarkRSOptions,
  BosOptions,
  // BOS/CHoCH/FVG types
  BosValue,
  CciOptions,
  ChannelLineOptions,
  ChannelLineValue,
  ChoppinessIndexOptions,
  CmfOptions,
  CmoOptions,
  ConnorsRsiOptions,
  ConnorsRsiValue,
  CoppockCurveOptions,
  CvdWithSignalOptions,
  CvdWithSignalValue,
  DemaOptions,
  DmiOptions,
  DmiValue,
  DonchianOptions,
  DonchianValue,
  DpoOptions,
  EaseOfMovementOptions,
  ElderForceIndexOptions,
  EmaRibbonOptions,
  EmaRibbonValue,
  FibonacciExtensionOptions,
  FibonacciExtensionValue,
  // Fibonacci Retracement types
  FibonacciRetracementOptions,
  FibonacciRetracementValue,
  FractalOptions,
  FractalValue,
  FramaOptions,
  FvgGap,
  FvgOptions,
  FvgValue,
  GapAnalysisOptions,
  GapValue,
  GarmanKlassOptions,
  HeikinAshiValue,
  HighestLowestValue,
  HistoricalVolatilityOptions,
  HmaOptions,
  HmmFeatureOptions,
  // HMM Regime Detection types
  HmmModel,
  HmmOptions,
  HmmRegimeOptions,
  HmmRegimeValue,
  HurstOptions,
  IchimokuOptions,
  IchimokuValue,
  ImiOptions,
  KamaOptions,
  KeltnerChannelOptions,
  KeltnerChannelValue,
  KillZoneDefinition,
  KillZoneValue,
  KlingerOptions,
  KlingerValue,
  KstOptions,
  KstValue,
  LinearRegressionOptions,
  LinearRegressionValue,
  LiquiditySweep,
  LiquiditySweepOptions,
  LiquiditySweepValue,
  MarketProfileOptions,
  MarketProfileValue,
  MassIndexOptions,
  McGinleyDynamicOptions,
  MfiOptions,
  MultiRSOptions,
  NviOptions,
  OpeningRangeOptions,
  OpeningRangeValue,
  // SMC types
  OrderBlock,
  OrderBlockOptions,
  OrderBlockValue,
  ParabolicSarOptions,
  ParabolicSarValue,
  PivotPointsOptions,
  PivotPointsValue,
  PpoOptions,
  PpoValue,
  PriceLevelSource,
  QstickOptions,
  RegimeTransitionInfo,
  RocOptions,
  RoofingFilterOptions,
  RSValue,
  SchaffTrendCycleOptions,
  SessionBreakoutOptions,
  SessionBreakoutValue,
  // Session / Kill Zone types
  SessionDefinition,
  SessionInfo,
  SessionStatsOptions,
  SessionStatsValue,
  SrZone,
  SrZonesOptions,
  SrZonesResult,
  StandardDeviationOptions,
  StochasticsOptions,
  StochasticsValue,
  StochRsiOptions,
  StochRsiValue,
  SuperSmootherOptions,
  SupertrendOptions,
  SupertrendValue,
  SwingPointOptions,
  SwingPointValue,
  SymbolRSRank,
  T3Options,
  TemaOptions,
  TrixOptions,
  TrixValue,
  TsiOptions,
  TsiValue,
  TwapOptions,
  UlcerIndexOptions,
  UltimateOscillatorOptions,
  VolumeMaOptions,
  VortexOptions,
  VortexValue,
  // Wyckoff types
  VsaBarType,
  VsaOptions,
  VsaValue,
  VwapBand,
  VwapOptions,
  VwapValue,
  VwmaOptions,
  WeisWaveOptions,
  WeisWaveValue,
  WilliamsROptions,
  WmaOptions,
  WyckoffEvent,
  WyckoffPhase,
  WyckoffPhaseOptions,
  WyckoffValue,
  ZigzagOptions,
  ZigzagValue,
  ZlemaOptions,
} from "./indicators";
// Indicators
// Volatility Regime indicator
export {
  adaptiveBollinger,
  adaptiveMa,
  // Adaptive Indicators
  adaptiveRsi,
  adaptiveStochastics,
  adl,
  adxr,
  alma,
  anchoredVwap,
  andrewsPitchfork,
  aroon,
  atr,
  atrPercentSeries,
  atrStops,
  // Auto Trend Line / Channel / Fibonacci Extension / Pitchfork
  autoTrendLine,
  awesomeOscillator,
  balanceOfPower,
  // Relative Strength
  benchmarkRS,
  // Volatility
  bollingerBands,
  bottomByRS,
  // BOS/CHoCH/FVG (SMC price structure)
  breakOfStructure,
  // ATR Filter (stock screening)
  calculateAtrPercent,
  calculateAtrStop,
  calculateAtrTakeProfit,
  calculateAtrTrailingStop,
  calculateRSRating,
  cci,
  chandelierExit,
  changeOfCharacter,
  channelLine,
  choppinessIndex,
  cmf,
  cmo,
  compareRS,
  connorsRsi,
  coppockCurve,
  cumulativeReturns,
  cvd,
  cvdWithSignal,
  DEFAULT_ATR_THRESHOLD,
  // Session / Kill Zones
  defineSession,
  dema,
  detectSessions,
  dmi,
  donchianChannel,
  dpo,
  easeOfMovement,
  elderForceIndex,
  ema,
  emaRibbon,
  fairValueGap,
  fastStochastics,
  fibonacciExtension,
  // Fibonacci Retracement
  fibonacciRetracement,
  filterByRSPercentile,
  filterStocksByAtr,
  fitHmm,
  // Fractals / Zigzag
  fractals,
  frama,
  gapAnalysis,
  garmanKlass,
  getActiveOrderBlocks,
  getAlternatingSwingPoints,
  getHkexSessions,
  getIctKillZones,
  getIctSessions,
  getJpxSessions,
  getNearestFvg,
  getNearestOrderBlock,
  getRecoveredSweeps,
  getSwingHighs,
  getSwingLows,
  getTzHourMinute,
  getUnfilledFvgs,
  hasRecentSweepSignal,
  // Heikin-Ashi
  heikinAshi,
  highest,
  // Price
  highestLowest,
  historicalVolatility,
  hma,
  // HMM Regime Detection
  hmmRegimes,
  hurst,
  // Trend
  ichimoku,
  imi,
  isInAnyBreak,
  isInSessionWindow,
  isOutperforming,
  kama,
  keltnerChannel,
  killZones,
  klinger,
  kst,
  linearRegression,
  liquiditySweep,
  lowest,
  macd,
  marketProfile,
  massIndex,
  mcginleyDynamic,
  // Price transforms
  medianPrice,
  mfi,
  nvi,
  obv,
  // Gap / Opening Range
  openingRange,
  // SMC (Smart Money Concepts)
  orderBlock,
  parabolicSar,
  passesAtrFilter,
  pivotPoints,
  ppo,
  pvt,
  qstick,
  rankByRS,
  regimeTransitionMatrix,
  returns,
  roc,
  roofingFilter,
  // Momentum
  rsi,
  schaffTrendCycle,
  sessionBreakout,
  sessionStats,
  slowStochastics,
  // Moving Averages
  sma,
  // S/R Zone Clustering
  srZones,
  srZonesSeries,
  standardDeviation,
  stochastics,
  stochRsi,
  // Filter (Ehlers)
  superSmoother,
  supertrend,
  swingPoints,
  t3,
  tema,
  topByRS,
  trix,
  tsi,
  twap,
  typicalPrice,
  ulcerIndex,
  ultimateOscillator,
  volatilityRegime,
  volumeAnomaly,
  // Volume
  volumeMa,
  volumeProfile,
  volumeProfileSeries,
  volumeTrend,
  vortex,
  // Wyckoff (VSA + Phase Detection)
  vsa,
  vwap,
  vwma,
  weightedClose,
  weisWave,
  williamsR,
  wma,
  wyckoffPhases,
  zigzag,
  zlema,
} from "./indicators";
// Incremental Indicator API
export * as incremental from "./indicators/incremental";
// Indicator Plugins (namespace)
export * as plugins from "./indicators/plugins";
// Safe indicator versions (Result-returning)
export * as safe from "./indicators/safe";
export type {
  // Anchored Walk-Forward types
  AnchoredWalkForwardOptions,
  AWFPeriod,
  AWFResult,
  CombinationResultEntry,
  CombinationSearchOptions,
  CombinationSearchResult,
  // Combination Search types
  ConditionDefinition,
  DnaGrade,
  DnaGradeItem,
  DnaGradeReport,
  // Strategy DNA types
  GenomeSegment,
  GridSearchOptions,
  GridSearchResult,
  MetricStatistics,
  // Monte Carlo types
  MonteCarloOptions,
  MonteCarloResult,
  OptimizationConstraint,
  OptimizationMetric,
  OptimizationResultEntry,
  // Optimization types
  ParameterRange,
  // Pareto types
  ParetoObjective,
  ParetoOptions,
  ParetoResult,
  ParetoResultEntry,
  PathParameterRange,
  // PBO (CSCV) types
  PboOptions,
  PboResult,
  RecommendedParams,
  SafeZone,
  SensitivityData,
  SensitivityPair,
  SensitivitySingle,
  StrategyFactory,
  WalkForwardOptions,
  WalkForwardPeriod,
  WalkForwardResult,
} from "./optimization";
// Optimization
export {
  // Anchored Walk-Forward Analysis
  anchoredWalkForwardAnalysis,
  anchoredWalkForwardAnalysisSafe,
  annualizeReturn,
  // Strategy DNA — post-optimization analytics
  buildGenomeSegments,
  calculateAllMetrics,
  calculateAWFPeriodCount,
  calculateCalmarRatio,
  calculatePeriodCount,
  calculateRecoveryFactor,
  // Metrics
  calculateSharpeRatio,
  calculateStatistics,
  // Combination Search
  combinationSearch,
  combinationSearchSafe,
  computeDnaGrade,
  computeRecommendedParams,
  constraint,
  countCombinations,
  countTotalCombinations,
  createEntryConditionPool,
  createExitConditionPool,
  crowdingDistance,
  extractSensitivityData,
  extractTradeReturns,
  fastNonDominatedSort,
  formatAWFResult,
  formatCombinationResult,
  formatMonteCarloResult,
  GRID_SEARCH_EPSILON_FACTOR,
  generateAWFBoundaries,
  generateCombinations,
  generateParameterCombinations,
  generatePeriodBoundaries,
  getAWFEquityCurve,
  getOutOfSampleEquityCurve,
  getTopCombinations,
  getTopResults,
  // Grid Search
  gridSearch,
  gridSearchFromJSON,
  gridSearchFromJSONSafe,
  gridSearchSafe,
  param,
  // Pareto (Multi-Objective) Optimization
  paretoOptimization,
  paretoOptimizationSafe,
  // Probability of Backtest Overfitting (CSCV)
  pbo,
  pboSafe,
  // Monte Carlo Simulation
  runMonteCarloSimulation,
  runMonteCarloSimulationSafe,
  stitchOosEquity,
  summarizeAWFResult,
  summarizeCombinationSearch,
  summarizeGridSearch,
  summarizeMonteCarloResult,
  summarizeParetoResult,
  summarizeWalkForward,
  // Walk-Forward Analysis
  walkForwardAnalysis,
  walkForwardAnalysisFromJSON,
  walkForwardAnalysisFromJSONSafe,
  walkForwardAnalysisSafe,
  wfeRatio,
} from "./optimization";
// Position Sizing
export {
  // ATR-based sizing
  atrBasedSize,
  calculateAtrStopDistance,
  calculateKellyPercent,
  calculateStopDistance,
  // Fixed fractional
  fixedFractionalSize,
  fractionForPositionCount,
  // Kelly criterion
  kellySize,
  maxPositions,
  recommendedAtrMultiplier,
  // Risk-based sizing
  riskBasedSize,
  riskPerShare,
} from "./position-sizing";
export type { DeflatedSharpeParams } from "./scoring";
// Signal Scoring
export {
  bullishVolumeTrend,
  // Calculator
  calculateScore,
  calculateScoreBreakdown,
  calculateScoreSeries,
  cmfPositive,
  createAggressivePreset,
  createBalancedPreset,
  createBearishVolumeTrendEvaluator,
  createBullishVolumeTrendEvaluator,
  createCmfNegativeEvaluator,
  createCmfPositiveEvaluator,
  createConservativePreset,
  createDeathCrossEvaluator,
  createGoldenCrossEvaluator,
  createHighVolumeUpCandleEvaluator,
  createMacdBearishEvaluator,
  createMacdBullishEvaluator,
  createMeanReversionPreset,
  createMomentumPreset,
  createPerfectOrderBearishEvaluator,
  createPerfectOrderBullishEvaluator,
  createPOConfirmationEvaluator,
  createPriceAboveEmaEvaluator,
  createPriceBelowEmaEvaluator,
  createPullbackEntryEvaluator,
  createRsiNeutralEvaluator,
  createRsiOverboughtEvaluator,
  // Signal evaluators
  createRsiOversoldEvaluator,
  createStochBullishCrossEvaluator,
  createStochOverboughtEvaluator,
  createStochOversoldEvaluator,
  createTrendFollowingPreset,
  createVolumeAnomalyEvaluator,
  createVolumeSpikeEvaluator,
  // Deflated Sharpe Ratio
  deflatedSharpe,
  deflatedSharpeFromReturns,
  expectedMaxSharpe,
  // Presets
  getPreset,
  goldenCross50200,
  highVolumeUpCandle,
  isScoreAbove,
  isScoreBelow,
  listPresets,
  macdBearish,
  macdBullish,
  minActiveSignals,
  minTrackRecordLength,
  perfectOrderBearish as poBearishSignal,
  perfectOrderBullish as poBullishSignal,
  perReturnSharpe,
  poConfirmation,
  priceAboveEma20,
  probabilisticSharpe,
  pullbackEntry20,
  rsiOverbought70,
  // Pre-built signals
  rsiOversold30,
  // Builder
  ScoreBuilder,
  // Backtest conditions
  scoreAbove,
  scoreBelow,
  scoreIncreasing,
  scoreStrength,
  scoreWithMinSignals,
  stochOverbought,
  stochOversold,
  volumeAnomaly2z,
  volumeSpike,
} from "./scoring";
export { parseCsv } from "./screening/csv-parser";
export { formatCsv, formatJson, formatTable } from "./screening/formatters";
// Screening (browser-compatible exports only - no fs dependency)
export {
  CONDITION_PRESETS,
  createCriteriaFromNames,
  getAvailableConditions,
  screenStock,
  screenStockSafe,
  screenStockSeries,
} from "./screening/screen-stock";
export type {
  // Candlestick Pattern types
  CandlestickPattern,
  CandlestickPatternName,
  CandlestickPatternOptions,
  CandlestickPatternValue,
  ChannelOptions,
  CoachingDirection,
  CoachingOptions,
  CoachingSeverity,
  // Coaching types
  CoachingSignal,
  CooldownConfig,
  CrossSignalQuality,
  CrossValidationOptions,
  CupHandleOptions,
  DebounceConfig,
  DivergenceClass,
  DivergenceOptions,
  DivergenceSignal,
  DoublePatternOptions,
  ExpiryConfig,
  FlagOptions,
  HarmonicPatternOptions,
  HarmonicPatternType,
  HeadShouldersOptions,
  ManagedSignal,
  PatternFilterOptions,
  PatternKeyPoint,
  PatternNeckline,
  PatternSignal,
  // Pattern types
  PatternType,
  PerfectOrderOptions,
  PerfectOrderOptionsEnhanced,
  PerfectOrderState,
  PerfectOrderType,
  PerfectOrderValue,
  PerfectOrderValueEnhanced,
  RangeBoundOptions,
  RangeBoundState,
  RangeBoundValue,
  SignalKeyFn,
  SignalManager,
  SignalManagerOptions,
  SignalManagerState,
  // Signal Lifecycle types
  SignalState,
  SlopeDirection,
  SqueezeOptions,
  SqueezeSignal,
  TrendlineFit,
  TrendlinePairType,
  TrendReason,
  TriangleOptions,
  VolumeAboveAverageOptions,
  VolumeAboveAverageSignal,
  VolumeAccumulationOptions,
  VolumeAccumulationSignal,
  VolumeBreakoutOptions,
  VolumeBreakoutSignal,
  VolumeMaCrossOptions,
  VolumeMaCrossSignal,
  WedgeOptions,
} from "./signals";
// Signals
export {
  bollingerSqueeze,
  // Candlestick Patterns
  candlestickPatterns,
  classifyTrendlinePair,
  // Signal Lifecycle
  createSignalManager,
  crossOver,
  crossUnder,
  cupWithHandle,
  cvdDivergence,
  deadCross,
  detectChannel,
  // Coaching
  detectCoachingSignals,
  detectDivergence,
  detectFlag,
  detectHarmonicPatterns,
  detectTriangle,
  detectWedge,
  doubleBottom,
  // Price Patterns
  doubleTop,
  filterPatterns,
  fitTrendline,
  fitTrendlinePair,
  // Trade Signal Converters
  fromCrossSignal,
  fromDivergenceSignal,
  fromPatternSignal,
  fromPipelineResult,
  fromScoreResult,
  fromSqueezeSignal,
  goldenCross,
  headAndShoulders,
  inverseHeadAndShoulders,
  macdDivergence,
  obvDivergence,
  perfectOrder,
  perfectOrderEnhanced,
  processSignalsBatch,
  rangeBound,
  rsiDivergence,
  validateCrossSignals,
  volumeAboveAverage,
  volumeAccumulation,
  volumeBreakout,
  volumeMaCross,
} from "./signals";
// Types
// Plugin system
// Portfolio types
// Result types
export type {
  AllocationStrategy,
  AtrBasedSizingOptions,
  AtrOptions,
  // ATR risk management types
  AtrRiskOptions,
  AtrStopsOptions,
  AtrStopsValue,
  AtrTrailingStopConfig,
  BacktestOptions,
  BacktestResult,
  BacktestSettings,
  BacktestSizingConfig,
  BacktestSizingConfigJSON,
  BacktestSizingContext,
  BatchBacktestOptions,
  BatchBacktestResult,
  BollingerBandsOptions,
  BollingerBandsValue,
  // Candle types
  Candle,
  ChandelierExitOptions,
  ChandelierExitValue,
  CombinedCondition,
  Condition,
  ConditionFn,
  CrossOptions,
  DrawdownPeriod,
  EmaOptions,
  EquityPoint,
  Err,
  ExitReason,
  FillMode,
  FixedFractionalOptions,
  // Fundamental metrics types
  FundamentalMetrics,
  HighestLowestOptions,
  IndicatorPlugin,
  // Indicator types
  IndicatorValue,
  KellySizingOptions,
  MacdOptions,
  // Indicator result types
  MacdValue,
  MtfConditionFn,
  // MTF types
  MtfContext,
  MtfDataset,
  MtfPresetCondition,
  NormalizedCandle,
  Ok,
  PartialTakeProfitConfig,
  PortfolioBacktestOptions,
  PortfolioBacktestResult,
  PortfolioMetrics,
  // Backtest types
  PositionDirection,
  PositionSizeResult,
  PositionSizingBaseOptions,
  PositionSizingMethod,
  PositionSizingOptions,
  PresetCondition,
  PriceLevels,
  PriceSource,
  RebalanceConfig,
  Result,
  ReturnsOptions,
  RiskBasedSizingOptions,
  RsiOptions,
  ScaledEntryConfig,
  ScaledEntryIntervalType,
  // Scaled entry types
  ScaledEntryStrategy,
  ScoreBreakdown,
  ScoreResult,
  ScoringConfig,
  ScoringPreset,
  Series,
  Signal,
  SignalContribution,
  SignalDefinition,
  // Scoring types
  SignalEvaluator,
  SignalReason,
  // Signal types
  SignalType,
  SlTpMode,
  // Option types
  SmaOptions,
  SymbolBacktestResult,
  SymbolData,
  // Timeframe types
  Timeframe,
  TimeframeShorthand,
  TimeframeUnit,
  Trade,
  // Trade Signal types
  TradeAction,
  TradeDirection,
  TradeSignal,
  TrendCraftError,
  TrendCraftErrorCode,
  // Volatility regime types
  VolatilityRegime,
  VolatilityRegimeOptions,
  VolatilityRegimeValue,
  // Volume analysis types
  VolumeAnomalyValue,
  VolumePriceLevel,
  VolumeProfileValue,
  VolumeTrendValue,
} from "./types";
export {
  collectResults,
  defineIndicator,
  err,
  flatMap,
  mapResult,
  ok,
  partitionResults,
  tcError,
  toResult,
  tryCatch,
  unwrap,
  unwrapOr,
} from "./types";

// Note: runScreening, loadCsvFile, getCsvFiles, loadCsvDirectory are Node.js-only
// Import from "trendcraft/screening" or "../src/screening" for CLI usage

// Alpha Decay Monitor
export {
  analyzeAlphaDecay,
  createObservationsFromScores,
  createObservationsFromTrades,
  spearmanCorrelation,
} from "./alpha-decay";
export type {
  BehaviorEquityPoint,
  // Behavior Insights types
  BehaviorInsight,
  DrawdownSummary,
  EventExtractor,
  EventHorizonStats,
  EventStudyBaseline,
  EventStudyOptions,
  EventStudyResult,
  ExitReasonAnalysis,
  HitRate,
  HoldingPeriodAnalysis,
  // Market Context types
  MarketContext,
  MarketContextOptions,
  MarketRegimeOptions,
  MarketRegimeResult,
  MfeMaeAnalysis,
  OmegaOptions,
  PatternProjection,
  PatternProjectionOptions,
  RegimeAttributionOptions,
  RegimeAttributionReport,
  RegimeLabel,
  RegimeStats,
  RegimeTransition,
  ReportOptions,
  RollingOptions,
  RuntimeMetrics,
  RuntimeMetricsOptions,
  StreakAnalysis,
  TearsheetReport,
  TearsheetSeries,
  TimeAnalysis,
  TradeAnalysis,
  TradeStats,
} from "./analysis";
// Trade Analysis
export {
  analyzeAllTrades,
  analyzeByExitReason,
  analyzeByHoldingPeriod,
  analyzeByTime,
  analyzeDrawdowns,
  // Market Context
  analyzeMarketContext,
  analyzeMfeMae,
  analyzeStreaks,
  // Regime-conditioned attribution
  backtestByRegime,
  calculateRuntimeMetrics,
  calculateTradeStats,
  // Return-distribution & rolling metrics
  captureRatios,
  commonSenseRatio,
  cpcIndex,
  detectMarketRegime,
  // Event study
  eventStudy,
  gainToPainRatio,
  // Behavior Insights
  generateBehaviorInsights,
  omegaRatio,
  payoffRatioFromReturns,
  profitFactorFromReturns,
  projectFromPatterns,
  projectFromSeries,
  projectPatternOutcome,
  // Tearsheet report
  report,
  rollingSharpe,
  rollingVolatility,
  sharpeFromReturns,
  sortinoFromReturns,
  tailRatio,
  winRateFromReturns,
} from "./analysis";
export type {
  BacktestScore,
  CompositeSlippageModel,
  FixedSlippageModel,
  LimitOrder,
  LimitPriceFunc,
  MarginConfig,
  MarginState,
  OrderType,
  PendingOrder,
  ScoreBreakdownEntry,
  ScoreOptions,
  ScoreWeights,
  SlippageModel,
  StopLimitOrder,
  StopOrder,
  StopPriceFunc,
  TimeInForce,
  VolatilitySlippageModel,
  VolumeSlippageModel,
} from "./backtest";
// Backtest Scoring
// Dynamic Slippage Model
// Order Types (Limit/Stop)
// Margin/Leverage
export {
  accrueInterest,
  calculateBuyingPower,
  calculateDynamicSlippage,
  checkMarginCall,
  createMarginState,
  freezeOrderPrices,
  limitAboveClose,
  limitAtHigh,
  limitAtLow,
  limitAtrAbove,
  limitAtrBelow,
  // Preset limit/stop strategies
  limitBelowClose,
  repayLoan,
  resolveSlippageModel,
  scoreBacktestResult,
  stopAboveHigh,
  stopAtrAbove,
  stopAtrBelow,
  stopBelowLow,
  tryFillOrder,
  updateMarginState,
} from "./backtest";
export type { AnnualizationOptions, TradingCalendar } from "./calendar";
// Trading calendar (market-specific annualization)
export {
  annualizationFactor,
  CRYPTO_CALENDAR,
  FX_CALENDAR,
  HKEX_CALENDAR,
  JPX_CALENDAR,
  US_EQUITY_CALENDAR,
} from "./calendar";
// Composable Indicator Algebra
export {
  applyIndicator,
  combineSeries,
  compose,
  extractField,
  mapValues,
  pipe,
  seriesToCandles,
  through,
} from "./compose";
export type {
  IndicatorAccessor,
  UnifiedCondition,
  UnifiedConditionDef,
} from "./conditions";
// Unified Conditions (define once, use in backtest & streaming)
export {
  defineUnifiedCondition,
  unifiedAnd,
  unifiedNot,
  unifiedOr,
} from "./conditions";
export { normalizeAndValidate } from "./core/normalize";
// Series tagging (chart rendering metadata)
export { tagSeries } from "./core/tag-series";
// Cross-Asset Correlation
export {
  analyzeCorrelation,
  analyzeLeadLag,
  detectCorrelationRegimes,
  detectIntermarketDivergence,
  pearsonCorrelation,
  rollingCorrelation,
  spearmanRankCorrelation,
} from "./correlation";
// Execution utilities (resilient order execution)
export * as execution from "./execution";
// Signal Explainability
export {
  explainCondition,
  explainSignal,
  generateNarrative,
  traceCondition,
} from "./explainability";
export type {
  EwmaVolatilityFromCandlesOptions,
  EwmaVolatilityOptions,
  GarchOptions,
  GarchResult,
} from "./indicators/volatility";
// GARCH / EWMA Volatility
export { ewmaVolatility, ewmaVolatilityFromCandles, garch } from "./indicators/volatility";
export type {
  EquityCurveAnalysis,
  EquityCurveFilterOptions,
  EquityCurveFilterType,
  EquityCurveHealthResult,
  StrategyAllocation,
  StrategyPerformanceMetric,
  StrategyRotationOptions,
  StrategyRotationResult,
} from "./meta-strategy";
// Meta-Strategy (Equity Curve Trading, Strategy Rotation)
export {
  applyEquityCurveFilter,
  equityCurveHealth,
  rotateStrategies,
} from "./meta-strategy";
export type {
  CandleFormerConfig,
  CandleFormerOptions,
  CandleFormerTrainOptions,
  CandleFormerTrainResult,
  CandleFormerValue,
  CandleFormerWeights,
  CandleToken,
  PredictionDirection,
} from "./ml";
// CandleFormer - ML-based candlestick prediction
export {
  candleFormer,
  candleFormerBearish,
  candleFormerBullish,
  classifyShape,
  DEFAULT_CONFIG as CANDLE_FORMER_DEFAULT_CONFIG,
  NUM_CLASSES,
  NUM_PATTERNS,
  NUM_SHAPES,
  NUM_VOLUME_BINS,
  PAD_TOKEN,
  PATTERN_NAMES,
  PATTERN_NONE,
  PATTERN_VOCAB_SIZE,
  quantizeCandle,
  SHAPE_NAMES,
  tokenizeCandles,
  tokenizePatterns,
  trainCandleFormer,
  VOCAB_SIZE,
} from "./ml";
// Pairs Trading / Cointegration
export {
  adfTest,
  analyzeMeanReversion,
  analyzePair,
  calculateSpread,
  olsRegression,
} from "./pairs";
export type {
  ConditionalDrawdownResult,
  CorrelationAdjustedSizeOptions,
  CorrelationAdjustedSizeResult,
  DrawdownBin,
  DrawdownDistribution,
  RecoveryEstimate,
  ReturnShock,
  RiskParityOptions,
  RiskParityResult,
  RollingVarOptions,
  RollingVarValue,
  StressScenario,
  StressTestResult,
  StressTestSummary,
  VarMethod,
  VarOptions,
  VarResult,
} from "./risk";
// Risk Analytics (VaR / CVaR / Risk Parity)
// Stress Testing / Scenario Analysis
// Deep Drawdown Analysis
export {
  calculateMetricsFromReturns,
  calculateVaR,
  conditionalDrawdown,
  correlationAdjustedSize,
  drawdownDistribution,
  estimateRecoveryTime,
  generateShockedReturns,
  PRESET_SCENARIOS,
  riskParityAllocation,
  rollingVaR,
  runAllStressTests,
  stressTest,
  ulcerPerformanceIndex,
} from "./risk";
// Strategy Robustness Score
export { calculateRobustnessScore, quickRobustnessScore, scoreToGrade } from "./robustness";
export type {
  CsvLoadError,
  CsvLoadResult,
  OutputFormat,
  ScreeningCriteria,
  ScreeningOptions,
  ScreeningResult,
  ScreeningSeriesPoint,
  ScreeningSeriesResult,
  ScreeningSessionResult,
  ScreenStockOptions,
  ScreenStockSeriesOptions,
} from "./screening";
// Strategy JSON Serialization
export type {
  ConditionCategory,
  ConditionParamSchema,
  ConditionRegistryEntry,
  ConditionSpec,
  LeafInfo,
  ParamDef,
  ParsedLeafPath,
  SessionOverrides,
  StrategyDefinition,
  StrategyJSON,
  Tunable,
  ValidationResult as StrategyValidationResult,
} from "./strategy";
// Strategy Definition
export * as strategy from "./strategy";
export {
  applyParamOverrides,
  backtestRegistry,
  ConditionRegistry,
  createSessionFromStrategy,
  flattenStrategyLeaves,
  hydrateCondition,
  listTunables,
  loadStrategy,
  parseLeafPath,
  parseStrategy,
  parseStrategySafe,
  serializeStrategy,
  streamingRegistry,
  validateConditionSpec,
  validateStrategyJSON,
} from "./strategy";
export type { IndicatorCategory, IndicatorPreset, LivePreset, ParamSchema } from "./streaming";
// Streaming (real-time trading pipeline)
export * as streaming from "./streaming";
export {
  createLiveCandle,
  getIndicatorPreset,
  getIndicatorPresetKey,
  indicatorPresets,
  livePresets,
} from "./streaming";
export type {
  AlphaDecayOptions,
  AlphaDecayResult,
  CointegrationResult,
  ConditionTrace,
  CorrelationAnalysisOptions,
  CorrelationAnalysisResult,
  CorrelationPoint,
  CorrelationRegime,
  CorrelationRegimePoint,
  CusumBreak,
  DecayAssessment,
  DecayObservation,
  DimensionScore,
  DivergencePoint,
  ExplainOptions,
  HitRatePoint,
  IndicatorFn,
  LeadLagResult,
  MeanReversionResult,
  PairsAnalysisOptions,
  PairsAnalysisResult,
  PairsSignal,
  QuickRobustnessOptions,
  QuickRobustnessResult,
  RobustnessGrade,
  RobustnessOptions,
  RobustnessResult,
  RollingICPoint,
  SeriesToCandlesOptions,
  SeriesTransformFn,
  SignalExplanation,
  SpreadPoint,
} from "./types";
export type { SeriesMeta, TaggedSeries } from "./types/candle";
// Series Utilities
export {
  alignAndNormalize,
  alignSeries,
  filterSeries,
  firstValidIndex,
  mapSeries,
  normalizeToPercent,
  trimWarmup,
  warmupBars,
  zipSeries,
} from "./utils/series";
export type {
  GapDetectionOptions,
  SpikeDetectionOptions,
  StaleDetectionOptions,
  ValidationFinding,
  ValidationOptions,
  ValidationResult,
  ValidationSeverity,
  VolumeAnomalyOptions,
} from "./validation";
// Validation
export {
  detectDuplicates,
  detectGaps,
  detectOhlcErrors,
  detectPriceSpikes,
  detectSplitHints,
  detectStaleData,
  detectVolumeAnomalies,
  removeDuplicates,
  validateCandles,
} from "./validation";
