/**
 * Indicator Catalog
 *
 * Static data definitions for all 77 indicators available in indicatorPresets.
 * Each entry includes human-readable metadata and parameter schemas for the sidebar UI.
 */

export type ParamDef = {
  key: string;
  label: string;
  type: "number";
  default: number;
  min?: number;
  max?: number;
  step?: number;
};

export type Category =
  | "Moving Averages"
  | "Momentum"
  | "Volatility"
  | "Trend"
  | "Volume"
  | "Price"
  | "Wyckoff";

export type IndicatorEntry = {
  id: string;
  name: string;
  shortName: string;
  description: string;
  category: Category;
  overlay: boolean;
  params: ParamDef[];
};

// Reusable param definitions
const period = (def = 14, min = 2, max = 200): ParamDef => ({
  key: "period",
  label: "Period",
  type: "number",
  default: def,
  min,
  max,
  step: 1,
});

export const CATEGORIES: Category[] = [
  "Moving Averages",
  "Momentum",
  "Volatility",
  "Trend",
  "Volume",
  "Price",
  "Wyckoff",
];

export const CATALOG: IndicatorEntry[] = [
  // ============================================
  // Moving Averages
  // ============================================
  {
    id: "sma",
    name: "Simple Moving Average",
    shortName: "SMA",
    description: "Equal-weighted mean of closing prices over a fixed window.",
    category: "Moving Averages",
    overlay: true,
    params: [period(20)],
  },
  {
    id: "ema",
    name: "Exponential Moving Average",
    shortName: "EMA",
    description: "Exponentially weighted average giving more weight to recent prices.",
    category: "Moving Averages",
    overlay: true,
    params: [period(20)],
  },
  {
    id: "wma",
    name: "Weighted Moving Average",
    shortName: "WMA",
    description: "Linearly weighted average emphasizing recent data points.",
    category: "Moving Averages",
    overlay: true,
    params: [period(20)],
  },
  {
    id: "vwma",
    name: "Volume Weighted Moving Average",
    shortName: "VWMA",
    description: "Moving average weighted by volume, highlighting high-activity price levels.",
    category: "Moving Averages",
    overlay: true,
    params: [period(20)],
  },
  {
    id: "kama",
    name: "Kaufman Adaptive Moving Average",
    shortName: "KAMA",
    description: "Adapts smoothing speed based on market noise using the efficiency ratio.",
    category: "Moving Averages",
    overlay: true,
    params: [period(10)],
  },
  {
    id: "hma",
    name: "Hull Moving Average",
    shortName: "HMA",
    description: "Reduces lag while maintaining smoothness using weighted moving averages.",
    category: "Moving Averages",
    overlay: true,
    params: [period(16)],
  },
  {
    id: "t3",
    name: "Tillson T3",
    shortName: "T3",
    description: "Ultra-smooth moving average using six cascaded exponential smoothing stages.",
    category: "Moving Averages",
    overlay: true,
    params: [period(5)],
  },
  {
    id: "mcginley",
    name: "McGinley Dynamic",
    shortName: "McGinley",
    description:
      "Self-adjusting moving average that tracks price more closely than traditional MAs.",
    category: "Moving Averages",
    overlay: true,
    params: [period(14)],
  },
  {
    id: "emaRibbon",
    name: "EMA Ribbon",
    shortName: "EMA Ribbon",
    description: "Multiple EMAs at different periods forming a visual ribbon for trend strength.",
    category: "Moving Averages",
    overlay: true,
    params: [],
  },
  {
    id: "dema",
    name: "Double Exponential Moving Average",
    shortName: "DEMA",
    description: "Reduces lag by applying EMA of EMA with a correction formula.",
    category: "Moving Averages",
    overlay: true,
    params: [period(20)],
  },
  {
    id: "tema",
    name: "Triple Exponential Moving Average",
    shortName: "TEMA",
    description: "Further reduces lag using triple EMA calculation.",
    category: "Moving Averages",
    overlay: true,
    params: [period(20)],
  },
  {
    id: "zlema",
    name: "Zero-Lag EMA",
    shortName: "ZLEMA",
    description: "Eliminates inherent EMA lag by applying a momentum correction.",
    category: "Moving Averages",
    overlay: true,
    params: [period(20)],
  },
  {
    id: "alma",
    name: "Arnaud Legoux Moving Average",
    shortName: "ALMA",
    description: "Gaussian-weighted moving average with configurable offset and sigma.",
    category: "Moving Averages",
    overlay: true,
    params: [
      period(9),
      { key: "offset", label: "Offset", type: "number", default: 0.85, min: 0, max: 1, step: 0.05 },
      { key: "sigma", label: "Sigma", type: "number", default: 6, min: 1, max: 20, step: 1 },
    ],
  },
  {
    id: "frama",
    name: "Fractal Adaptive Moving Average",
    shortName: "FRAMA",
    description: "Adapts to market fractal dimension, speeding up in trends and slowing in ranges.",
    category: "Moving Averages",
    overlay: true,
    params: [period(16)],
  },

  // ============================================
  // Momentum
  // ============================================
  {
    id: "rsi",
    name: "Relative Strength Index",
    shortName: "RSI",
    description: "Measures overbought/oversold conditions on a 0-100 scale.",
    category: "Momentum",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "macd",
    name: "Moving Average Convergence Divergence",
    shortName: "MACD",
    description: "Trend-following momentum indicator showing the relationship between two EMAs.",
    category: "Momentum",
    overlay: false,
    params: [
      { key: "fastPeriod", label: "Fast", type: "number", default: 12, min: 2, max: 100, step: 1 },
      { key: "slowPeriod", label: "Slow", type: "number", default: 26, min: 2, max: 200, step: 1 },
      {
        key: "signalPeriod",
        label: "Signal",
        type: "number",
        default: 9,
        min: 2,
        max: 50,
        step: 1,
      },
    ],
  },
  {
    id: "stochastics",
    name: "Stochastic Oscillator",
    shortName: "Stoch",
    description: "Compares closing price to its range over a lookback period (0-100).",
    category: "Momentum",
    overlay: false,
    params: [
      {
        key: "kPeriod",
        label: "%K Period",
        type: "number",
        default: 14,
        min: 2,
        max: 100,
        step: 1,
      },
      { key: "dPeriod", label: "%D Period", type: "number", default: 3, min: 1, max: 50, step: 1 },
      { key: "slowing", label: "Slowing", type: "number", default: 3, min: 1, max: 10, step: 1 },
    ],
  },
  {
    id: "dmi",
    name: "Directional Movement Index",
    shortName: "DMI/ADX",
    description: "Measures trend strength (ADX) and direction (+DI/-DI).",
    category: "Momentum",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "roc",
    name: "Rate of Change",
    shortName: "ROC",
    description: "Percentage change in price over a specified number of periods.",
    category: "Momentum",
    overlay: false,
    params: [period(12)],
  },
  {
    id: "williamsR",
    name: "Williams %R",
    shortName: "Williams %R",
    description: "Oscillator measuring overbought/oversold levels on a -100 to 0 scale.",
    category: "Momentum",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "cci",
    name: "Commodity Channel Index",
    shortName: "CCI",
    description: "Measures deviation from the statistical mean, centered at zero.",
    category: "Momentum",
    overlay: false,
    params: [period(20)],
  },
  {
    id: "stochRsi",
    name: "Stochastic RSI",
    shortName: "StochRSI",
    description: "Applies stochastic calculation to RSI for more sensitive signals.",
    category: "Momentum",
    overlay: false,
    params: [
      {
        key: "rsiPeriod",
        label: "RSI Period",
        type: "number",
        default: 14,
        min: 2,
        max: 50,
        step: 1,
      },
      {
        key: "stochPeriod",
        label: "Stoch Period",
        type: "number",
        default: 14,
        min: 2,
        max: 50,
        step: 1,
      },
      { key: "kPeriod", label: "%K", type: "number", default: 3, min: 1, max: 20, step: 1 },
      { key: "dPeriod", label: "%D", type: "number", default: 3, min: 1, max: 20, step: 1 },
    ],
  },
  {
    id: "trix",
    name: "Triple Exponential Average",
    shortName: "TRIX",
    description: "Rate of change of a triple-smoothed EMA, filtering short-term noise.",
    category: "Momentum",
    overlay: false,
    params: [period(15)],
  },
  {
    id: "aroon",
    name: "Aroon Indicator",
    shortName: "Aroon",
    description: "Identifies trend changes and strength using highs/lows timing.",
    category: "Momentum",
    overlay: false,
    params: [period(25)],
  },
  {
    id: "connorsRsi",
    name: "Connors RSI",
    shortName: "CRSI",
    description: "Composite RSI combining price RSI, streak RSI, and ROC percentile.",
    category: "Momentum",
    overlay: false,
    params: [
      {
        key: "rsiPeriod",
        label: "RSI Period",
        type: "number",
        default: 3,
        min: 2,
        max: 20,
        step: 1,
      },
      {
        key: "streakPeriod",
        label: "Streak",
        type: "number",
        default: 2,
        min: 2,
        max: 20,
        step: 1,
      },
      {
        key: "rocPeriod",
        label: "ROC Period",
        type: "number",
        default: 100,
        min: 10,
        max: 200,
        step: 1,
      },
    ],
  },
  {
    id: "cmo",
    name: "Chande Momentum Oscillator",
    shortName: "CMO",
    description: "Measures momentum on a -100 to +100 scale using up/down day ratios.",
    category: "Momentum",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "adxr",
    name: "ADX Rating",
    shortName: "ADXR",
    description: "Smoothed ADX providing a lagged measure of trend strength.",
    category: "Momentum",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "imi",
    name: "Intraday Momentum Index",
    shortName: "IMI",
    description: "Volume-weighted RSI variant using open-close relationships (0-100).",
    category: "Momentum",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "vortex",
    name: "Vortex Indicator",
    shortName: "Vortex",
    description: "Identifies trend direction using positive and negative trend movements.",
    category: "Momentum",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "ao",
    name: "Awesome Oscillator",
    shortName: "AO",
    description: "Difference between 5-period and 34-period SMA of median prices.",
    category: "Momentum",
    overlay: false,
    params: [
      { key: "fastPeriod", label: "Fast", type: "number", default: 5, min: 2, max: 20, step: 1 },
      { key: "slowPeriod", label: "Slow", type: "number", default: 34, min: 10, max: 100, step: 1 },
    ],
  },
  {
    id: "bop",
    name: "Balance of Power",
    shortName: "BOP",
    description: "Measures the strength of buyers vs sellers using OHLC data (-1 to +1).",
    category: "Momentum",
    overlay: false,
    params: [
      {
        key: "smoothPeriod",
        label: "Smooth",
        type: "number",
        default: 14,
        min: 1,
        max: 50,
        step: 1,
      },
    ],
  },
  {
    id: "qstick",
    name: "QStick",
    shortName: "QStick",
    description: "Running average of close minus open, indicating buying/selling pressure.",
    category: "Momentum",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "ppo",
    name: "Percentage Price Oscillator",
    shortName: "PPO",
    description: "MACD expressed as a percentage for comparing assets at different price levels.",
    category: "Momentum",
    overlay: false,
    params: [
      { key: "fastPeriod", label: "Fast", type: "number", default: 12, min: 2, max: 100, step: 1 },
      { key: "slowPeriod", label: "Slow", type: "number", default: 26, min: 2, max: 200, step: 1 },
      {
        key: "signalPeriod",
        label: "Signal",
        type: "number",
        default: 9,
        min: 2,
        max: 50,
        step: 1,
      },
    ],
  },
  {
    id: "coppock",
    name: "Coppock Curve",
    shortName: "Coppock",
    description:
      "Long-term momentum oscillator originally designed to identify major market bottoms.",
    category: "Momentum",
    overlay: false,
    params: [
      { key: "wmaPeriod", label: "WMA", type: "number", default: 10, min: 2, max: 50, step: 1 },
      {
        key: "longRocPeriod",
        label: "Long ROC",
        type: "number",
        default: 14,
        min: 5,
        max: 50,
        step: 1,
      },
      {
        key: "shortRocPeriod",
        label: "Short ROC",
        type: "number",
        default: 11,
        min: 5,
        max: 50,
        step: 1,
      },
    ],
  },
  {
    id: "massIndex",
    name: "Mass Index",
    shortName: "Mass Index",
    description:
      "Detects trend reversals by measuring the narrowing/widening of the high-low range.",
    category: "Momentum",
    overlay: false,
    params: [
      {
        key: "emaPeriod",
        label: "EMA Period",
        type: "number",
        default: 9,
        min: 2,
        max: 30,
        step: 1,
      },
      {
        key: "sumPeriod",
        label: "Sum Period",
        type: "number",
        default: 25,
        min: 5,
        max: 50,
        step: 1,
      },
    ],
  },
  {
    id: "dpo",
    name: "Detrended Price Oscillator",
    shortName: "DPO",
    description: "Removes trend to identify cycles by comparing price to a displaced MA.",
    category: "Momentum",
    overlay: false,
    params: [period(20)],
  },
  {
    id: "ultimateOscillator",
    name: "Ultimate Oscillator",
    shortName: "UO",
    description: "Multi-timeframe oscillator combining three different periods (0-100).",
    category: "Momentum",
    overlay: false,
    params: [
      { key: "period1", label: "Period 1", type: "number", default: 7, min: 2, max: 30, step: 1 },
      { key: "period2", label: "Period 2", type: "number", default: 14, min: 5, max: 50, step: 1 },
      {
        key: "period3",
        label: "Period 3",
        type: "number",
        default: 28,
        min: 10,
        max: 100,
        step: 1,
      },
    ],
  },
  {
    id: "tsi",
    name: "True Strength Index",
    shortName: "TSI",
    description:
      "Double-smoothed momentum oscillator showing trend direction and overbought/oversold.",
    category: "Momentum",
    overlay: false,
    params: [
      { key: "longPeriod", label: "Long", type: "number", default: 25, min: 5, max: 50, step: 1 },
      { key: "shortPeriod", label: "Short", type: "number", default: 13, min: 2, max: 30, step: 1 },
      {
        key: "signalPeriod",
        label: "Signal",
        type: "number",
        default: 7,
        min: 2,
        max: 20,
        step: 1,
      },
    ],
  },
  {
    id: "kst",
    name: "Know Sure Thing",
    shortName: "KST",
    description: "Momentum oscillator based on smoothed rate-of-change across four timeframes.",
    category: "Momentum",
    overlay: false,
    params: [
      {
        key: "signalPeriod",
        label: "Signal",
        type: "number",
        default: 9,
        min: 2,
        max: 30,
        step: 1,
      },
    ],
  },
  {
    id: "hurst",
    name: "Hurst Exponent",
    shortName: "Hurst",
    description: "Measures trend persistence (>0.5 trending, <0.5 mean-reverting, ~0.5 random).",
    category: "Momentum",
    overlay: false,
    params: [
      {
        key: "minWindow",
        label: "Min Window",
        type: "number",
        default: 20,
        min: 10,
        max: 50,
        step: 1,
      },
      {
        key: "maxWindow",
        label: "Max Window",
        type: "number",
        default: 100,
        min: 50,
        max: 300,
        step: 10,
      },
    ],
  },
  {
    id: "stc",
    name: "Schaff Trend Cycle",
    shortName: "STC",
    description: "Combines MACD with stochastic smoothing for faster cycle detection (0-100).",
    category: "Momentum",
    overlay: false,
    params: [
      { key: "fastPeriod", label: "Fast", type: "number", default: 23, min: 5, max: 50, step: 1 },
      { key: "slowPeriod", label: "Slow", type: "number", default: 50, min: 20, max: 100, step: 1 },
      { key: "cyclePeriod", label: "Cycle", type: "number", default: 10, min: 2, max: 30, step: 1 },
    ],
  },

  // ============================================
  // Volatility
  // ============================================
  {
    id: "atr",
    name: "Average True Range",
    shortName: "ATR",
    description: "Measures market volatility using the range of each period's price movement.",
    category: "Volatility",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "bb",
    name: "Bollinger Bands",
    shortName: "BB",
    description: "SMA with upper/lower bands at standard deviation intervals.",
    category: "Volatility",
    overlay: true,
    params: [
      period(20),
      { key: "stdDev", label: "Std Dev", type: "number", default: 2, min: 0.5, max: 5, step: 0.5 },
    ],
  },
  {
    id: "donchian",
    name: "Donchian Channel",
    shortName: "Donchian",
    description: "Highest high and lowest low over a lookback period, defining breakout levels.",
    category: "Volatility",
    overlay: true,
    params: [period(20)],
  },
  {
    id: "keltner",
    name: "Keltner Channel",
    shortName: "Keltner",
    description: "EMA-based channel using ATR for band width.",
    category: "Volatility",
    overlay: true,
    params: [
      {
        key: "emaPeriod",
        label: "EMA Period",
        type: "number",
        default: 20,
        min: 5,
        max: 50,
        step: 1,
      },
      {
        key: "atrPeriod",
        label: "ATR Period",
        type: "number",
        default: 10,
        min: 5,
        max: 50,
        step: 1,
      },
      {
        key: "multiplier",
        label: "Multiplier",
        type: "number",
        default: 1.5,
        min: 0.5,
        max: 5,
        step: 0.5,
      },
    ],
  },
  {
    id: "chandelierExit",
    name: "Chandelier Exit",
    shortName: "Chandelier",
    description: "Trailing stop-loss levels based on ATR from the highest high / lowest low.",
    category: "Volatility",
    overlay: true,
    params: [
      period(22),
      {
        key: "multiplier",
        label: "Multiplier",
        type: "number",
        default: 3,
        min: 1,
        max: 10,
        step: 0.5,
      },
    ],
  },
  {
    id: "choppiness",
    name: "Choppiness Index",
    shortName: "CHOP",
    description: "Determines if the market is choppy (range-bound) or trending (0-100).",
    category: "Volatility",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "garmanKlass",
    name: "Garman-Klass Volatility",
    shortName: "GK Vol",
    description:
      "Efficient volatility estimator using OHLC data, more accurate than close-to-close.",
    category: "Volatility",
    overlay: false,
    params: [
      period(20),
      {
        key: "annualFactor",
        label: "Annual Factor",
        type: "number",
        default: 252,
        min: 1,
        max: 365,
        step: 1,
      },
    ],
  },
  {
    id: "hv",
    name: "Historical Volatility",
    shortName: "HV",
    description: "Annualized standard deviation of logarithmic returns.",
    category: "Volatility",
    overlay: false,
    params: [
      period(20),
      {
        key: "annualFactor",
        label: "Annual Factor",
        type: "number",
        default: 252,
        min: 1,
        max: 365,
        step: 1,
      },
    ],
  },
  {
    id: "atrStops",
    name: "ATR Stops",
    shortName: "ATR Stops",
    description: "Stop-loss and take-profit levels calculated from ATR multiples.",
    category: "Volatility",
    overlay: true,
    params: [
      period(14),
      {
        key: "stopMultiplier",
        label: "Stop Mult",
        type: "number",
        default: 2,
        min: 0.5,
        max: 10,
        step: 0.5,
      },
      {
        key: "takeProfitMultiplier",
        label: "TP Mult",
        type: "number",
        default: 3,
        min: 0.5,
        max: 10,
        step: 0.5,
      },
    ],
  },
  {
    id: "ulcer",
    name: "Ulcer Index",
    shortName: "Ulcer",
    description: "Measures downside volatility and drawdown depth.",
    category: "Volatility",
    overlay: false,
    params: [period(14)],
  },

  // ============================================
  // Trend
  // ============================================
  {
    id: "supertrend",
    name: "Supertrend",
    shortName: "Supertrend",
    description: "Trend-following overlay that flips between support and resistance based on ATR.",
    category: "Trend",
    overlay: true,
    params: [
      period(10),
      {
        key: "multiplier",
        label: "Multiplier",
        type: "number",
        default: 3,
        min: 1,
        max: 10,
        step: 0.5,
      },
    ],
  },
  {
    id: "parabolicSar",
    name: "Parabolic SAR",
    shortName: "PSAR",
    description: "Trailing dot indicator for stop-and-reverse trend following.",
    category: "Trend",
    overlay: true,
    params: [
      {
        key: "step",
        label: "Step",
        type: "number",
        default: 0.02,
        min: 0.01,
        max: 0.1,
        step: 0.01,
      },
      { key: "max", label: "Max", type: "number", default: 0.2, min: 0.1, max: 0.5, step: 0.05 },
    ],
  },
  {
    id: "ichimoku",
    name: "Ichimoku Cloud",
    shortName: "Ichimoku",
    description: "Multi-component trend system with cloud, conversion, and base lines.",
    category: "Trend",
    overlay: true,
    params: [
      {
        key: "tenkanPeriod",
        label: "Tenkan",
        type: "number",
        default: 9,
        min: 2,
        max: 30,
        step: 1,
      },
      { key: "kijunPeriod", label: "Kijun", type: "number", default: 26, min: 5, max: 60, step: 1 },
      {
        key: "senkouBPeriod",
        label: "Senkou B",
        type: "number",
        default: 52,
        min: 10,
        max: 120,
        step: 1,
      },
    ],
  },

  // ============================================
  // Volume
  // ============================================
  {
    id: "obv",
    name: "On-Balance Volume",
    shortName: "OBV",
    description:
      "Cumulative volume indicator that adds volume on up days and subtracts on down days.",
    category: "Volume",
    overlay: false,
    params: [],
  },
  {
    id: "cmf",
    name: "Chaikin Money Flow",
    shortName: "CMF",
    description:
      "Measures buying/selling pressure over a period using volume and price position (-1 to +1).",
    category: "Volume",
    overlay: false,
    params: [period(20)],
  },
  {
    id: "mfi",
    name: "Money Flow Index",
    shortName: "MFI",
    description: "Volume-weighted RSI measuring overbought/oversold conditions (0-100).",
    category: "Volume",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "vwap",
    name: "Volume Weighted Average Price",
    shortName: "VWAP",
    description: "Cumulative average price weighted by volume, key institutional benchmark.",
    category: "Volume",
    overlay: true,
    params: [],
  },
  {
    id: "adl",
    name: "Accumulation/Distribution Line",
    shortName: "ADL",
    description:
      "Cumulative indicator measuring money flow based on close position within the range.",
    category: "Volume",
    overlay: false,
    params: [],
  },
  {
    id: "twap",
    name: "Time Weighted Average Price",
    shortName: "TWAP",
    description: "Simple average of typical prices over time, used as execution benchmark.",
    category: "Volume",
    overlay: true,
    params: [],
  },
  {
    id: "elderForceIndex",
    name: "Elder Force Index",
    shortName: "EFI",
    description: "Combines price change and volume to measure the power behind price movements.",
    category: "Volume",
    overlay: false,
    params: [period(13)],
  },
  {
    id: "volumeAnomaly",
    name: "Volume Anomaly",
    shortName: "Vol Anomaly",
    description: "Detects abnormal volume spikes using z-score analysis.",
    category: "Volume",
    overlay: false,
    params: [],
  },
  {
    id: "klinger",
    name: "Klinger Volume Oscillator",
    shortName: "Klinger",
    description: "Compares short and long-term volume flow to predict price reversals.",
    category: "Volume",
    overlay: false,
    params: [
      {
        key: "shortPeriod",
        label: "Short",
        type: "number",
        default: 34,
        min: 10,
        max: 100,
        step: 1,
      },
      { key: "longPeriod", label: "Long", type: "number", default: 55, min: 20, max: 200, step: 1 },
      {
        key: "signalPeriod",
        label: "Signal",
        type: "number",
        default: 13,
        min: 2,
        max: 30,
        step: 1,
      },
    ],
  },
  {
    id: "pvt",
    name: "Price Volume Trend",
    shortName: "PVT",
    description: "Cumulative volume weighted by percentage price change.",
    category: "Volume",
    overlay: false,
    params: [],
  },
  {
    id: "nvi",
    name: "Negative Volume Index",
    shortName: "NVI",
    description: "Tracks price changes on days when volume decreases from the prior day.",
    category: "Volume",
    overlay: false,
    params: [],
  },
  {
    id: "cvd",
    name: "Cumulative Volume Delta",
    shortName: "CVD",
    description: "Approximates order flow by accumulating buying vs selling volume.",
    category: "Volume",
    overlay: false,
    params: [],
  },
  {
    id: "weisWave",
    name: "Weis Wave",
    shortName: "Weis Wave",
    description: "Accumulates volume into waves based on price swing direction.",
    category: "Volume",
    overlay: false,
    params: [],
  },
  {
    id: "anchoredVwap",
    name: "Anchored VWAP",
    shortName: "Anch. VWAP",
    description: "VWAP calculated from a user-specified anchor point in time.",
    category: "Volume",
    overlay: true,
    params: [],
  },
  {
    id: "emv",
    name: "Ease of Movement",
    shortName: "EMV",
    description: "Relates price change to volume, measuring how easily price moves.",
    category: "Volume",
    overlay: false,
    params: [period(14)],
  },
  {
    id: "volumeTrend",
    name: "Volume Trend",
    shortName: "Vol Trend",
    description: "Combines price trend analysis with volume confirmation signals.",
    category: "Volume",
    overlay: false,
    params: [
      {
        key: "pricePeriod",
        label: "Price Period",
        type: "number",
        default: 10,
        min: 2,
        max: 50,
        step: 1,
      },
      {
        key: "volumePeriod",
        label: "Vol Period",
        type: "number",
        default: 10,
        min: 2,
        max: 50,
        step: 1,
      },
      {
        key: "maPeriod",
        label: "MA Period",
        type: "number",
        default: 20,
        min: 5,
        max: 100,
        step: 1,
      },
    ],
  },

  // ============================================
  // Price
  // ============================================
  {
    id: "highestLowest",
    name: "Highest / Lowest",
    shortName: "Hi/Lo",
    description: "Tracks the highest high and lowest low over a rolling window.",
    category: "Price",
    overlay: true,
    params: [period(20)],
  },
  {
    id: "pivotPoints",
    name: "Pivot Points",
    shortName: "Pivots",
    description: "Classic support/resistance levels calculated from prior period's OHLC.",
    category: "Price",
    overlay: true,
    params: [],
  },
  {
    id: "fractals",
    name: "Williams Fractals",
    shortName: "Fractals",
    description: "Marks local highs and lows using surrounding bar comparison.",
    category: "Price",
    overlay: true,
    params: [period(2, 1, 10)],
  },
  {
    id: "gapAnalysis",
    name: "Gap Analysis",
    shortName: "Gaps",
    description:
      "Detects price gaps between consecutive candles. Requires real market data with overnight gaps.",
    category: "Price",
    overlay: false,
    params: [
      {
        key: "minGapPercent",
        label: "Min Gap %",
        type: "number",
        default: 0.5,
        min: 0,
        max: 5,
        step: 0.1,
      },
    ],
  },
  {
    id: "orb",
    name: "Opening Range Breakout",
    shortName: "ORB",
    description: "Identifies breakouts from the opening range. Requires intraday data.",
    category: "Price",
    overlay: true,
    params: [
      { key: "minutes", label: "Minutes", type: "number", default: 30, min: 5, max: 120, step: 5 },
    ],
  },
  {
    id: "fvg",
    name: "Fair Value Gap",
    shortName: "FVG",
    description: "Detects imbalance zones where price moved too fast, leaving unfilled gaps.",
    category: "Price",
    overlay: true,
    params: [
      {
        key: "minGapPercent",
        label: "Min Gap %",
        type: "number",
        default: 0,
        min: 0,
        max: 5,
        step: 0.1,
      },
      {
        key: "maxActiveFvgs",
        label: "Max Active",
        type: "number",
        default: 10,
        min: 1,
        max: 50,
        step: 1,
      },
    ],
  },

  // ============================================
  // Wyckoff
  // ============================================
  {
    id: "vsa",
    name: "Volume Spread Analysis",
    shortName: "VSA",
    description:
      "Classifies bar types based on price spread and volume relationships (Wyckoff method).",
    category: "Wyckoff",
    overlay: false,
    params: [
      {
        key: "volumeMaPeriod",
        label: "Vol MA",
        type: "number",
        default: 20,
        min: 5,
        max: 50,
        step: 1,
      },
      {
        key: "atrPeriod",
        label: "ATR Period",
        type: "number",
        default: 14,
        min: 5,
        max: 50,
        step: 1,
      },
    ],
  },
];
